#Just stores data (NO logic)

# Should contain:
# HOST_A_IP = "10.0.1.10"
# HOST_B_IP = "10.0.2.20"

# HOST_A_MAC = "AA:AA"
# ROUTER_MAC = "BB:BB"
# HOST_B_MAC = "CC:CC"

HOST_A_NAME = "Host A"
HOST_B_NAME = "Host B"

HOST_A_IP = "10.0.1.10"
HOST_B_IP = "10.0.2.20"

HOST_A_MAC = "AA:AA:AA:AA:AA:AA"
HOST_B_MAC = "DD:DD:DD:DD:DD:DD"

ROUTER_NAME = "Router R1"
ROUTER_IF1_IP = "10.0.1.1"
ROUTER_IF2_IP = "10.0.2.1"
ROUTER_IF1_MAC = "BB:BB:BB:BB:BB:BB"
ROUTER_IF2_MAC = "CC:CC:CC:CC:CC:CC"