HOST_A_NAME = "Host A"
HOST_B_NAME = "Host B"
HOST_A_IP = "10.0.1.10"
HOST_B_IP = "10.0.2.20"
HOST_A_MAC = "AA:AA:AA:AA:AA:AA"
HOST_B_MAC = "DD:DD:DD:DD:DD:DD"
ROUTER_NAME = "Router R1"
ROUTER_IF1_IP = "10.0.1.1"
ROUTER_IF2_IP = "10.0.2.1"
ROUTER_IF1_MAC = "BB:BB:BB:BB:BB:BB"
ROUTER_IF2_MAC = "CC:CC:CC:CC:CC:CC"

HOST_INTERFACE = "eth0"
ROUTER_INTERFACE_1 = "Interface 1"
ROUTER_INTERFACE_2 = "Interface 2"


DEFAULT_SOURCE_PORT = 5000
DEFAULT_DESTINATION_PORT = 80


TTL = 100
HOST_A_PORT = 5000
HOST_B_PORT = 80

HOST_A_MAC_TABLE = {
    ROUTER_IF1_IP: ROUTER_IF1_MAC,
}

HOST_B_MAC_TABLE = {
    ROUTER_IF2_IP: ROUTER_IF2_MAC,
}

ROUTER_IF1_MAC_TABLE = {
    HOST_A_IP: HOST_A_MAC,
}

ROUTER_IF2_MAC_TABLE = {
    HOST_B_IP: HOST_B_MAC,
}

HOST_A_ROUTING_TABLE = {
    HOST_B_IP: (ROUTER_IF1_IP, HOST_INTERFACE),
}

HOST_B_ROUTING_TABLE = {
    HOST_A_IP: (ROUTER_IF2_IP, HOST_INTERFACE),
}

ROUTER_ROUTING_TABLE = {
    HOST_A_IP: (HOST_A_IP, ROUTER_INTERFACE_1),
    HOST_B_IP: (HOST_B_IP, ROUTER_INTERFACE_2),
}

ROUTER_MAC_TABLE = {
    HOST_A_IP: HOST_A_MAC,
    HOST_B_IP: HOST_B_MAC,
}
